### PR TITLE
Let there be CI

### PR DESCRIPTION
**Pull request by oddstr13**
Thanks to @h1dden-da3m0n who did all the hard work :heart:

### CODE REVIEW

**Review by crobibero — APPROVED** [review]
Still think most of these workflows should be added to the meta repo if possible

**Comment by h1dden-da3m0n** [comment]
> Still think most of these workflows should be added to the meta repo if possible

Well, IIRC you can load/import workflow yaml files (similar to what u can do with GitLab-CI) but I have never done it on GitHub.
Keep in mind though that you still would have to have a file importing the definition (*SHOULD IT WORK THAT WAY*)

**Comment by oddstr13** [comment]
Well, yes, managing the versions and stuff in one repo would be better, but this makes it work *right now*!

**Comment by h1dden-da3m0n** [comment]
> Well, yes, managing the versions and stuff in one repo would be better, but this makes it work _right now_!

I will work on that next :wink:. Centralizing the build/workflow configs sounds like a great idea and I want to play with importing workflows anyway.

**Comment by h1dden-da3m0n** [comment]
Okay, did a bit more digging regarding the centralized workflow definition. Unfortunately it seems that is currently not supported by GH Actions. ([public GitHub Roadmap](https://github.com/github/roadmap/issues/98))
However, according to the this [GitHub Forum Disussion](https://github.community/t/being-dry-centralized-workflows/16548/6) something like a `Composite Run Step` is possible, which I'll try out and see if we could use it to accomplish centralized workflows for the here hosted plugins.

edit:
Well, unfortunately it turns out that a `Composite Run Step`, while definitely interesting, wont be too useful for our aim to centrlise the plugin workflows. [Here the docs](https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action) if you are interested (it basically uses a version of the actual GH action definition to provide the 'composite' behaviour).
However, this finding might have sparked an idea regarding the `jprm` repo that I will share after thinking about it a bit more thoroughly and still consider it a 'good' idea after that :wink:

**Pull request merged**
